services:
  mongodb:
    image: mongo:7
    container_name: ddland-mongodb
    restart: unless-stopped
    ports:
      - "16261:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ddland

volumes:
  mongodb_data:
